# -*- coding: utf-8 -*-
"""Novartis_Challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cYOAmXeBd2X8UGaOq1jqrE4GoER0VPS4
"""

import pandas as pd
train = pd.read_csv('/content/Train.csv')
train.head()

train.isnull().sum()

test = pd.read_csv('/content/Test.csv')
test.head()

test.isnull().sum()

import numpy as np
age_array = train[train["X_12"]!=np.nan]["X_12"]
train["X_12"] = train["X_12"].replace(np.nan,age_array.median())
test["X_12"] = test["X_12"].replace(np.nan,age_array.median())

train = train.drop(columns=['DATE'],axis=1)

test = test.drop(columns=['DATE'],axis=1)

train.head()

X= train.iloc[:,1:16].values
Y = train.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

tes = test.iloc[:,1:16].values

from xgboost import XGBClassifier
model = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=500, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)
model.fit(X_train,y_train,eval_metric='auc')

prediction = model.predict(X_test)

from sklearn.metrics import recall_score, f1_score
print ('F1 score:', f1_score(y_test, prediction))
print ('Recall:', recall_score(y_test, prediction))

pred = model.predict(tes)

submission = pd.DataFrame({ 'INCIDENT_ID': test.INCIDENT_ID, 'MULTIPLE_OFFENSE': pred})
submission.to_csv('result.csv', index=False)

submission.head(10)

